[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_SUPABASE_URL = "https://qphpmmouslvtuaicblla.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaHBtbW91c2x2dHVhaWNibGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODYxMDYsImV4cCI6MjA2ODI2MjEwNn0.FsquqPZmIreayai-ASVEm5gkUsXYYeoCl0mQfDzhmk"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200